services:
  - type: web
    name: five-hundred
    runtime: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
